baseURL = '/'
languageCode = 'ru-RU'
title = 'My New Hugo Site'
staticDir = ["static"]
# uglyURLs = true
canonifyURLs = true
relativeURLs = true

[[section_templates]]
  name = "company"
  layout = "services"
  [section_templates.permalinks]
    permalink = "/company/:slug/"

    [[section_templates]]
      name = "client"
      layout = "services"
      [section_templates.permalinks]
        permalink = "/client/:slug/"


[[section_templates]]
  name = "colocation"
  layout = "services"
  [section_templates.permalinks]
    permalink = "/services/colocation/:slug/"

[[section_templates]]
  name = "dedicated"
  layout = "services"
  [section_templates.permalinks]
    permalink = "/services/dedicated/:slug/"

[[section_templates]]
  name = "other"
  layout = "services"
  [section_templates.permalinks]
    permalink = "/services/other/:slug/"

[[section_templates]]
  name = "software"
  layout = "services"
  [section_templates.permalinks]
    permalink = "/services/software/:slug/"

params = ["params"]

[[menu.main]]
    name = "Компания"
    weight = 1

    [[menu.main]]
        name = "O нас"
        url = "/company/about"
        parent = "Компания"
        weight = 5

    [[menu.main]]
        name = "Схема проезда"
        url = "/company/map"
        parent = "Компания"
        weight = 6

    [[menu.main]]
        name = "Реквизиты"
        url = "/company/details"
        parent = "Компания"
        weight = 7

    [[menu.main]]
        name = "Контакты"
        url = "/company/contacts"
        parent = "Компания"
        weight = 8

[[menu.main]]
	name = "Услуги"
	weight = 2

	[[menu.main]]
         name = "Размещение серверного оборудования"
         url = "/services/colocation"
         parent = "Услуги"
         weight = 9

    [[menu.main]]
         name = "Аренда сервера"
         url = "/services/dedicated"
         parent = "Услуги"
         weight = 10

    [[menu.main]]
         name = "Программное обеспечение"
         url = "/services/software"
         parent = "Услуги"
         weight = 11

    [[menu.main]]
         name = "Другие услуги"
         url = "/services/other"
         parent = "Услуги"
         weight = 12


[[menu.main]]
	name = "Клиентам"
	weight = 3

		[[menu.main]]
             name = "Как разместить сервер"
             url = "/client/instruction"
             parent = "Клиентам"
             weight = 13

        [[menu.main]]
             name = "Способы оплаты"
             url = "/client/payments"
             parent = "Клиентам"
             weight = 14

        [[menu.main]]
             name = "Техническая поддержка"
             url = "/client/support"
             parent = "Клиентам"
             weight = 15

        [[menu.main]]
             name = "Документы"
             url = "/client/document"
             parent = "Клиентам"
             weight = 16

        [[menu.main]]
              name = "Правила посещения дата-центра"
              url = "/client/visited"
              parent = "Клиентам"
              weight = 17

[[menu.main]]
    name = "Инфо"
    weight = 4
        [[menu.main]]
             name = "Советы"
             url = "/info/articles"
             parent = "Инфо"
             weight = 18

        [[menu.main]]
             name = "Отзывы"
             url = "/info/review"
             parent = "Инфо"
             weight = 19

        [[menu.main]]
              name = "Партнерская программа"
              url = "/info/partners"
              parent = "Инфо"
              weight = 20



[[menu.footer]]
name = "О компании"
url = "/company/about"
weight = 1


[[menu.footer]]
name = "Услуга Colocation"
url = "/services/colocation"
weight = 2

[[menu.footer]]
name = "Аренда сервера"
url = "/services/dedicated"
weight = 3


[[menu.footer]]
name = "Клиентам"
url = "/client/instruction"
weight = 4


[[menu.footer]]
name = "Партнерам"
url = "/info/partners"
weight = 5


[[menu.footer]]
name = "Инфо"
url = "/info/articles"
weight = 6
